[versions]
accompanist = "0.25.1"
activity = "1.7.2"
annotation = "1.7.0"
apollo = "3.8.1"
appcompat = "1.6.1"
appdistribution-feedback = "16.0.0-beta10"
appdistribution-gradle = "4.0.0"
androidx-work = "2.8.1"
automator = "2.2.0"
coil = "2.4.0"
collect-dispatcher = "1.1.0"
compose = "1.5.1"
compose-compiler = "1.5.3"
compose-multiplatform = "1.5.1"
core = "1.12.0"
coroutines = "1.7.3"
crash-reporter = "1.1.0"
dagger = "2.48"
datetime = "0.4.0"
desugar = "2.0.3"
detekt = "1.22.0"
espresso = "3.5.1"
exoplayer = "1.1.1"
firebase-bom = "32.2.3"
gradle = "8.1.2"
gson = "2.9.1"
inject = "1"
install-referrer = "1.1.0"
junit = "4.13.2"
kotlin = "1.9.10"
ksp = "1.9.10-1.0.13"
ktor = "2.2.4"
ktor-server = "2.3.3"
leakcanary = "2.10"
lifecycle = "2.6.2"
log = "1.3.6"
lottie = "6.0.0"
maps = "2.11.4"
maps-utils = "3.4.0"
material3 = "1.1.1"
mockk = "1.13.7"
okhttp = "3.8.0"
optimizely = "3.10.1"
orchestrator = "1.4.2"
performance-plugin = "1.4.2"
play-location = "21.0.1"
play-maps = "18.1.0"
precompose = "1.5.5"
retrofit = "2.5.0"
rules = "1.5.0"
runner = "1.5.2"
serialization = "1.5.0"
services = "4.3.15"
splash = "1.0.1"
sqldelight = "1.5.5"
tagmanagement-dispatcher = "1.2.0"
tealium = "1.5.2"
tealium-lifecycle = "1.1.1"
tealium-remotecommands-contentsquare = "2.0.0"
tealium-remotecommands-dispatcher = "1.2.0"
tealium-remotecommands-firebase = "1.2.0"
zoomable = "1.4.3"
koin = "3.5.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqldelight" }

[libraries]
android-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-appcompat-resources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "appcompat" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-tooling-ui = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-splash = { group = "androidx.core", name = "core-splashscreen", version.ref = "splash" }
androidx-test-compose-ui-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-test-compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "material3" }
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "orchestrator" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-test-ui-automator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "automator" }
androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }

apollo-cache = { group = "com.apollographql.apollo3", name = "apollo-normalized-cache", version.ref = "apollo" }
apollo-cache-sql = { group = "com.apollographql.apollo3", name = "apollo-normalized-cache-sqlite", version.ref = "apollo" }
apollo-runtime = { group = "com.apollographql.apollo3", name = "apollo-runtime", version.ref = "apollo" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-rules-libraries = { group = "io.gitlab.arturbosch.detekt", name = "detekt-rules-libraries", version.ref = "detekt" }
detekt-rules-ruleauthors = { group = "io.gitlab.arturbosch.detekt", name = "detekt-rules-ruleauthors", version.ref = "detekt" }

firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-appdistribution-feedback = { group = "com.google.firebase", name = "firebase-appdistribution-api-ktx", version.ref = "appdistribution-feedback" }
firebase-appdistribution-feedback-alpha = { group = "com.google.firebase", name = "firebase-appdistribution", version.ref = "appdistribution-feedback" }
firebase-appdistribution-gradle = { group = "com.google.firebase", name = "firebase-appdistribution-gradle", version.ref = "appdistribution-gradle" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-config = { group = "com.google.firebase", name = "firebase-config-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf-ktx" }
firebase-performance-plugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "performance-plugin" }

google-accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist" }
google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
google-accompanist-placeholder-material = { group = "com.google.accompanist", name = "accompanist-placeholder-material", version.ref = "accompanist" }
google-accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanist" }
google-accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
google-dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
google-dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
google-maps = { group = "com.google.maps.android", name = "maps-compose", version.ref = "maps" }
google-maps-compose-utils = { group = "com.google.maps.android", name = "maps-compose-utils", version.ref = "maps" }
google-maps-utils = { group = "com.google.maps.android", name = "maps-utils-ktx", version.ref = "maps-utils" }
google-play-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-location" }
google-play-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "play-maps" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "services" }

javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "inject" }

jetbrains-compose-foundation-layout = { group = "org.jetbrains.compose.foundation", name = "foundation-layout", version.ref = "compose-multiplatform" }
jetbrains-compose-material-ripple = { group = "org.jetbrains.compose.material", name = "material-ripple", version.ref = "compose-multiplatform" }
jetbrains-compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose-multiplatform" }
jetbrains-compose-ui-geometry = { group = "org.jetbrains.compose.ui", name = "ui-geometry", version.ref = "compose-multiplatform" }
jetbrains-compose-ui-graphics = { group = "org.jetbrains.compose.ui", name = "ui-graphics", version.ref = "compose-multiplatform" }
jetbrains-compose-ui-text = { group = "org.jetbrains.compose.ui", name = "ui-text", version.ref = "compose-multiplatform" }
jetbrains-compose-ui-unit = { group = "org.jetbrains.compose.ui", name = "ui-unit", version.ref = "compose-multiplatform" }
jetbrains-compose-ui-util = { group = "org.jetbrains.compose.ui", name = "ui-util", version.ref = "compose-multiplatform" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

ktor-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor-server" }
ktor-server-host-common = { group = "io.ktor", name = "ktor-server-host-common", version.ref = "ktor-server" }
ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio", version.ref = "ktor-server" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }


leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }

lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "exoplayer" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "exoplayer" }

optimizely-android = { group = "com.optimizely.ab", name = "android-sdk", version.ref = "optimizely" }
optimizely-log = { group = "com.noveogroup.android", name = "android-logger", version.ref = "log" }

precompose = { group = "moe.tlaster", name = "precompose", version.ref = "precompose" }
precompose-viewmodel = { group = "moe.tlaster", name = "precompose-viewmodel", version.ref = "precompose" }

sqldelight-android-driver = { group = "com.squareup.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-coroutines-extensions = { group = "com.squareup.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-native-driver = { group = "com.squareup.sqldelight", name = "native-driver", version.ref = "sqldelight" }
sqldelight-plugin = { group = "com.squareup.sqldelight", name = "gradle-plugin", version.ref = "sqldelight" }
sqldelight-sqlite-driver = { group = "com.squareup.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }

tealium-collect-dispatcher = { group = "com.tealium", name = "kotlin-collect-dispatcher", version.ref = "collect-dispatcher" }
tealium-core = { group = "com.tealium", name = "kotlin-core", version.ref = "tealium" }
tealium-crash-reporter = { group = "com.tealium", name = "kotlin-crash-reporter", version.ref = "crash-reporter" }
tealium-install-referrer = { group = "com.tealium", name = "kotlin-install-referrer", version.ref = "install-referrer" }
tealium-lifecycle = { group = "com.tealium", name = "kotlin-lifecycle", version.ref = "tealium-lifecycle" }
tealium-remotecommands-contentsquare = { group = "com.tealium.remotecommands", name = "contentsquare", version.ref = "tealium-remotecommands-contentsquare" }
tealium-remotecommands-dispatcher = { group = "com.tealium", name = "kotlin-remotecommand-dispatcher", version.ref = "tealium-remotecommands-dispatcher" }
tealium-remotecommands-firebase = { group = "com.tealium.remotecommands", name = "firebase", version.ref = "tealium-remotecommands-firebase" }
tealium-tagmanagement-dispatcher = { group = "com.tealium", name = "kotlin-tagmanagement-dispatcher", version.ref = "tagmanagement-dispatcher" }

mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-jvm = { group = "io.mockk", name = "mockk-jvm", version.ref = "mockk" }

zoomable = { group = "net.engawapg.lib", name = "zoomable", version.ref = "zoomable" }
